### ISSUE TITLE
After some runnings, "System Events" crash :(

### ISSUE THREAD

**Issue by kopiro** [andrehaveman/spotify-node-applescript#16]
{ [Error: /Users/kopiro/Projects/AnythingPlayableServer/node_modules/spotify-node-applescript/lib/scripts/get_artwork.applescript:981:1027: execution error: System Events got an error: Application isn’t running. (-600)
]
  appleScript: '/Users/kopiro/Projects/AnythingPlayableServer/node_modules/spotify-node-applescript/lib/scripts/get_artwork.applescript',
  exitCode: 1 } undefined

**Comment by andrehaveman** [comment]
get_artwork is has been removed because it's no longer supported, so I'm closing this issue.
